version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    pull-request-limit: 10
    cooldown: 5
    semver-minor-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    pull-request-limit: 10
    cooldown: 5
    semver-minor-days: 7
